# Generated by Django 3.1.14 on 2025-03-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20250316_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previuos_evolution',
            new_name='previous_evolution',
        ),
    ]
